import assert from 'node:assert/strict';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const playwrightPath=process.env.PLAYWRIGHT_PATH,url=process.env.IINA_CONTINUE_SIDEBAR_URL;
assert.ok(playwrightPath,'PLAYWRIGHT_PATH is required');assert.ok(url,'IINA_CONTINUE_SIDEBAR_URL is required');
const {chromium}=await import(pathToFileURL(`${playwrightPath}/index.mjs`));
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
const page=await browser.newPage({viewport:{width:360,height:700},colorScheme:'dark',locale:'en-US'});
await page.addInitScript(()=>{window.iina={handlers:{},postMessage(){},onMessage(name,callback){this.handlers[name]=callback}}});
await page.goto(url,{waitUntil:'domcontentloaded'});
await page.evaluate(()=>window.iina.handlers.status({language:'en',phase:'idle',active:false,message:'Choose a playback quality, then click Start.'}));
let result=await page.evaluate(()=>({action:document.querySelector('#action').textContent,buttons:document.querySelectorAll('button').length,hasLink:!!document.querySelector('input'),qrHidden:document.querySelector('#qr').hidden,qrChildren:document.querySelector('#qr').children.length,scroll:[document.documentElement.clientHeight,document.documentElement.scrollHeight]}));
assert.equal(result.action,'Start');assert.equal(result.buttons,1);assert.equal(result.hasLink,false);assert.equal(result.qrHidden,true);assert.equal(result.qrChildren,0);assert.deepEqual(result.scroll,[700,700]);assert.equal(await page.locator('#phase').count(),0);
await page.evaluate(()=>window.iina.handlers.status({language:'en',phase:'waiting',active:true,url:'http://10.0.0.2:1234/s/abcdefghijklmnopqrstuvwxyz/',message:'Scan the QR code.'}));
result=await page.evaluate(()=>{const qr=document.querySelector('#qr'),cover=getComputedStyle(qr,'::after');return{action:document.querySelector('#action').textContent,backdrop:cover.webkitBackdropFilter||cover.backdropFilter,opacity:cover.opacity,cursor:getComputedStyle(qr).cursor,hasSecurity:!!document.querySelector('#security'),title:qr.getAttribute('title'),pressed:qr.getAttribute('aria-pressed'),children:qr.children.length,hidden:qr.hidden}});
assert.equal(result.action,'End');assert.match(result.backdrop,/blur\(14px\)/);assert.equal(result.opacity,'1');assert.equal(result.cursor,'pointer');assert.equal(result.hasSecurity,false);assert.equal(result.title,null);assert.equal(result.pressed,'false');assert.equal(result.hidden,false);assert.ok(result.children>0);
await page.hover('#qr');await page.waitForTimeout(350);assert.equal(await page.locator('#qr').evaluate(el=>getComputedStyle(el,'::after').opacity),'0');
await page.mouse.move(1,1);await page.waitForTimeout(350);assert.equal(await page.locator('#qr').evaluate(el=>getComputedStyle(el,'::after').opacity),'1');
await page.focus('#qr');await page.keyboard.press('Enter');assert.equal(await page.locator('#qr').getAttribute('aria-pressed'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('#qr').getAttribute('aria-pressed'),'false');
const childrenBefore=await page.locator('#qr').evaluate(el=>el.children.length);
await page.evaluate(()=>window.iina.handlers.status({language:'en',phase:'connected',active:true,url:'http://10.0.0.2:1234/s/abcdefghijklmnopqrstuvwxyz/',message:'Phone connected.'}));
assert.equal(await page.locator('#qr').evaluate(el=>el.children.length),childrenBefore);
await page.waitForTimeout(350);
assert.equal(await page.locator('#qr').evaluate(el=>getComputedStyle(el,'::after').opacity),'1');
await page.screenshot({path:join(tmpdir(),'iina-continue-sidebar-active-dark.png')});
await page.locator('#qr').dispatchEvent('pointermove');await page.waitForTimeout(350);assert.equal(await page.locator('#qr').evaluate(el=>getComputedStyle(el,'::after').opacity),'0');
await page.evaluate(()=>window.iina.handlers.status({language:'en',phase:'ending',active:true,url:'http://10.0.0.2:1234/s/abcdefghijklmnopqrstuvwxyz/',message:'Ending Continue.'}));
assert.equal(await page.locator('#qr').evaluate(el=>el.children.length),childrenBefore);
await page.evaluate(()=>window.iina.handlers.status({language:'en',phase:'ended',active:false,message:'Continue ended.'}));
assert.equal(await page.locator('#qr').evaluate(el=>el.children.length),0);assert.equal(await page.locator('#qr').evaluate(el=>el.hidden),true);assert.equal(await page.locator('#action').textContent(),'Start');
await page.screenshot({path:join(tmpdir(),'iina-continue-sidebar-dark.png')});await browser.close();
