(function(){
  var core=iina.core,mpv=iina.mpv,menu=iina.menu,event=iina.event,utils=iina.utils,file=iina.file,sidebar=iina.sidebar,prefs=iina.preferences;
  var locales=typeof utils.preferredLocalizations==="function"?utils.preferredLocalizations():[],language=/^zh\b/i.test(locales[0]||"")?"zh":"en";
  var version=(core.getVersion&&core.getVersion().iina)||"0",v=String(version).match(/^(\d+)\.(\d+)/),iinaSupported=!!v&&(+v[1]>1||(+v[1]===1&&+v[2]>=4)),architecture="checking",supported=false,menuItem=null;
  var copy={
    zh:{checking:"正在检查兼容性…",idle:"请在选择播放画质后点击开始续播",oldIINA:"Continue 需要 IINA 1.4.0 或更高版本（当前为 "+version+"）",appleSilicon:"Continue 暂仅支持搭载 M 系列芯片的 Mac",noFile:"请先在 IINA 中播放一个本地文件",unsupported:"当前仅支持本地普通文件",current:"当前文件",starting:"启动中…",missingBin:"续播服务不可用，请尝试重新安装插件",startFailed:"续播服务启动失败：",preparing:"正在同步至另一个设备…",continueFailed:"同步失败：",returning:"正在同步至 IINA…",returnFailed:"返回 IINA 失败：",ending:"正在结束续播服务…",ended:"续播服务已结束，可从 IINA 重新开始",noAddress:"续播服务地址获取失败",waiting:"已启动，请扫描二维码连接另一个设备",connected:"已连接，请在打开的页面中点击播放",phone:"正在另一个设备播放，在 IINA 中点击播放即可返回",mac:"正在 IINA 播放，在另一个设备中点击播放即可续播",disconnected:"连接已断开，请检查网络连接",phoneEnded:"续播服务已结束，播放信息已同步至 IINA",expired:"续播服务超时，请从 IINA 重新开始",interrupted:"续播服务意外停止，请从 IINA 重新开始",processingFailed:"文件处理失败，请尝试其他播放画质",unknown:"未知错误"},
    en:{checking:"Checking compatibility…",idle:"Choose a playback quality, then click Start.",oldIINA:"Continue requires IINA 1.4.0 or later (current: "+version+").",appleSilicon:"Continue currently supports Apple silicon Macs only.",noFile:"Play a local file in IINA first.",unsupported:"Only standard local media files are supported.",current:"Current File",starting:"Starting…",missingBin:"Continue is unavailable. Try reinstalling the plugin.",startFailed:"Could not start Continue: ",preparing:"Syncing playback information to the other device…",continueFailed:"Could not continue on the other device: ",returning:"Syncing playback information back to IINA…",returnFailed:"Could not continue in IINA: ",ending:"Ending Continue…",ended:"Continue has ended. Click Start in IINA to begin again.",noAddress:"Could not get the address for Continue.",waiting:"Ready. Scan the QR code to connect another device.",connected:"Connected. Tap Play on the other device to continue there.",phone:"Playing on your other device. Press Play in IINA to continue here.",mac:"Playing in IINA. Tap Play on the other device to continue there.",disconnected:"Connection to the other device was lost. Check the network on both devices.",phoneEnded:"Continue ended and playback information was synced back to IINA.",expired:"Continue timed out. Click Start in IINA to begin again.",interrupted:"Continue was interrupted. Click Start in IINA to begin again.",processingFailed:"The file could not be processed. Try another playback quality.",unknown:"Unknown error."}
  };
  function t(key){return copy[language][key]}
  function helperError(code){var known={media_info:language==="zh"?"无法读取当前文件信息":"The current file information could not be read.",unrecognized_media:language==="zh"?"无法识别当前文件":"The current file could not be recognized."};return known[code]||(t("startFailed")+t("unknown"))}
  var helper=null,rest="",starting=false,pendingBin=null,sidebarLoaded=false,trackSyncTimer=null,cancelStarting=false,endingByUser=false;
  function baseState(){if(!iinaSupported)return{phase:"unsupported",message:t("oldIINA")};if(architecture==="checking")return{phase:"checking",message:t("checking")};if(architecture!=="supported")return{phase:"unsupported",message:t("appleSilicon")};return{phase:"idle",message:t("idle")}}
  var uiState=baseState();uiState.language=language;
  function deliver(view){try{view.postMessage("status",uiState)}catch(e){}}
  function status(data){data.language=language;data.active=starting||!!helper;uiState=data;if(sidebarLoaded)deliver(sidebar)}
  function setLanguage(locale){var next=/^zh\b/i.test(locale||"")?"zh":"en";if(next===language)return;language=next;if(menuItem)menuItem.title=language==="zh"?"开始续播":"Continue on";if(["checking","idle","unsupported"].indexOf(uiState.phase)>=0)status(baseState());else{uiState.language=language;if(sidebarLoaded)deliver(sidebar)}}
  function toggleSession(){if(!supported)return;if(starting||helper)endSession();else start()}
  function bind(view){
    view.onMessage("getState",function(){deliver(view)});view.onMessage("language",setLanguage);view.onMessage("toggleSession",toggleSession);
    view.onMessage("quality",function(q){if(["auto","original","1080p","720p"].indexOf(q)>=0){prefs.set("quality",q);prefs.sync()}});
  }
  function loadSidebar(force){if(sidebarLoaded&&!force)return;try{sidebar.loadFile("ui/continue.html")}catch(e){return}bind(sidebar);sidebarLoaded=true;deliver(sidebar)}
  function checkPlatform(){if(!iinaSupported)return;utils.exec("/usr/sbin/sysctl",["-n","hw.optional.arm64"]).then(function(r){if(r&&r.status===0){architecture=String(r.stdout||"").trim()==="1"?"supported":"unsupported"}else architecture="unknown";supported=architecture==="supported";status(baseState())}).catch(function(){architecture="unknown";supported=false;status(baseState())})}
  function parse(chunk){var lines=(rest+chunk).split("\n");rest=lines.pop();lines.forEach(function(line){try{var x=JSON.parse(line);if(x.event==="ready")onReady(x);else if(x.event==="phone")onPhone(x.data||{});else if(x.event==="continued")onContinued(x.session||{})}catch(e){}})}
  function pluginsDir(data){var p=(data||"").replace(/\/+$/ ,"");var i=p.lastIndexOf("/.data/");return i<0?null:p.slice(0,i)}
  function resolveBin(cb){var cached;try{cached=file.read("@data/bindir.txt")}catch(e){}if(cached&&cached.trim()){cached=cached.trim();if(file.exists(cached+"/continue-helper")&&file.exists(cached+"/ffmpeg")&&file.exists(cached+"/ffprobe")){cb(cached);return}}var base=pluginsDir(utils.resolvePath("@data/"));if(!base){cb(null);return}var done=false;function finish(p){if(done)return;done=true;p=(p||"").trim();if(p){file.write("@data/bindir.txt",p);cb(p)}else cb(null)}var script='for d in "$1"/*/; do if /usr/bin/grep -qs \'"identifier": *"dev.mzzp.iina-continue"\' "$d/Info.json"; then h="$d"bin/continue-helper; f="$d"bin/ffmpeg; p="$d"bin/ffprobe; if [ -x "$h" ] && [ -x "$f" ] && [ -x "$p" ]; then printf %s "$d"bin; exit 0; fi; exit 3; fi; done; exit 1';utils.exec("/bin/sh",["-c",script,"sh",base],null,function(s){if(s)finish(String(s))}).then(function(r){if(!done)finish(r&&r.status===0?r.stdout:null)}).catch(function(){finish(null)})}
  function describeError(e){if(!e)return t("unknown");if(typeof e==="string")return e;if(e.stderr)return String(e.stderr).trim();if(e.message)return String(e.message);try{return JSON.stringify(e)}catch(_){return String(e)}}
  function selectedTracks(){var out={audioIndex:-1,subtitleIndex:-1,subtitlePath:"",subtitleDelay:mpv.getNumber("sub-delay")||0,secondarySubtitleIndex:-1,secondarySubtitlePath:"",secondarySubtitleDelay:mpv.getNumber("secondary-sub-delay")||0},tracks=mpv.getNative("track-list")||[],sid=mpv.getString("sid"),secondary=mpv.getString("secondary-sid");tracks.forEach(function(track){var n=typeof track["ff-index"]==="number"?track["ff-index"]:-1;if(track.type==="audio"&&track.selected)out.audioIndex=n;if(track.type!=="sub")return;if(String(track.id)===sid||(track.selected&&out.subtitleIndex<0)){out.subtitleIndex=n;out.subtitlePath=track["external-filename"]||""}if(String(track.id)===secondary){out.secondarySubtitleIndex=n;out.secondarySubtitlePath=track["external-filename"]||""}});if(out.secondarySubtitleIndex===out.subtitleIndex&&out.secondarySubtitlePath===out.subtitlePath){out.secondarySubtitleIndex=-1;out.secondarySubtitlePath=""}return out}
  function start(){
    if(starting||helper)return;if(core.status.idle||core.status.isNetworkResource){status({phase:"error",message:t("noFile")});return}
    var src=mpv.getString("path")||core.status.url;if(!src){status({phase:"error",message:t("unsupported")});return}if(src.indexOf("file://")===0){try{src=decodeURIComponent(src.replace(/^file:\/\/(localhost)?/,""))}catch(e){src=src.replace(/^file:\/\/(localhost)?/,"")}}
    if(!src||/^[a-z][a-z0-9+.-]*:\/\//i.test(src)){status({phase:"error",message:t("unsupported")});return}
    var media={sourcePath:src,title:mpv.getString("media-title")||core.status.title||t("current"),durationSeconds:mpv.getNumber("duration")||core.status.duration||0,startPositionSeconds:mpv.getNumber("time-pos")||core.status.position||0,quality:prefs.get("quality")||"auto"};
    var tracks=selectedTracks();Object.keys(tracks).forEach(function(k){media[k]=tracks[k]});starting=true;cancelStarting=false;core.pause();status({phase:"starting",message:t("starting")});
    resolveBin(function(bin){if(cancelStarting){starting=false;return}if(!bin){starting=false;status({phase:"error",message:t("missingBin")});return}pendingBin=bin;utils.exec(bin+"/continue-helper",["--ffmpeg",bin+"/ffmpeg","--ffprobe",bin+"/ffprobe","--parent",String(mpv.getNumber("pid")||0),"--session",JSON.stringify(media)],null,parse,function(s){var m=String(s||"").trim();if(m)iina.console.log("[helper] "+m.slice(0,600))}).then(function(){var unexpected=!!helper;helper=null;starting=false;if(unexpected)status({phase:"error",message:t("interrupted")})}).catch(function(e){helper=null;starting=false;if(!cancelStarting)status({phase:"error",message:t("startFailed")+describeError(e)})})})
  }
  function client(path,body){return utils.exec(helper.bin+"/continue-helper",["client","--method","POST","--url","http://127.0.0.1:"+helper.port+path,"--secret",helper.secret,"--body",JSON.stringify(body||{})])}
  function continueSession(){if(!helper||(helper.state!=="mac"&&helper.state!=="waiting")||starting)return;var p=mpv.getNumber("time-pos")||core.status.position||0,q=prefs.get("quality")||"auto",body={positionSeconds:p,quality:q},tracks=selectedTracks();Object.keys(tracks).forEach(function(k){body[k]=tracks[k]});starting=true;core.pause();status({phase:"starting",url:helper.session.url,message:t("preparing")});client("/control/continue",body).catch(function(e){starting=false;status({phase:"error",url:helper&&helper.session.url,message:t("continueFailed")+describeError(e)})})}
  function scheduleTrackSync(){if(trackSyncTimer)clearTimeout(trackSyncTimer);trackSyncTimer=setTimeout(function(){trackSyncTimer=null;if(helper&&helper.state==="waiting"&&!starting)continueSession()},100)}
  function takeBack(){if(!helper||helper.state!=="phone")return;helper.state="returning";status({phase:"returning",url:helper.session.url,message:t("returning")});client("/control/take-back").catch(function(e){if(helper)helper.state="phone";status({phase:"error",url:helper&&helper.session.url,message:t("returnFailed")+describeError(e)})})}
  function endSession(){endingByUser=true;if(starting&&!helper){cancelStarting=true;starting=false;status({phase:"ended",message:t("ended")});return}if(!helper)return;status({phase:"ending",url:helper.session.url,message:t("ending")});client("/control/end").catch(function(){internalStop();starting=false;endingByUser=false;status({phase:"ended",message:t("ended")})})}
  function onReady(x){starting=false;if(cancelStarting){if(x.session&&x.session.url){helper={port:x.port,secret:x.controlSecret,bin:pendingBin,session:x.session,state:"waiting",connected:false};internalStop()}return}if(x.error){status({phase:"error",message:helperError(x.error)});return}var s=x.session;if(!s||!s.url){status({phase:"error",message:t("noAddress")});return}helper={port:x.port,secret:x.controlSecret,bin:pendingBin,session:s,state:"waiting",connected:false};if(s.state==="ERROR"){internalStop();status({phase:"error",message:t("processingFailed")});return}status({phase:"waiting",url:s.url,message:t("waiting")})}
  function onContinued(s){starting=false;if(!helper)return;helper.session=s;helper.state="waiting";if(s.state==="ERROR"){internalStop();status({phase:"error",message:t("processingFailed")});return}status({phase:helper.connected?"connected":"waiting",url:s.url,message:helper.connected?t("connected"):t("waiting")})}
  function onPhone(e){if(e.type==="connected"){if(helper){helper.connected=true;if(helper.state==="waiting")status({phase:"connected",url:helper.session.url,message:t("connected")})}}else if(e.type==="ready"){if(helper){helper.connected=true;helper.state="phone"}core.pause();status({phase:"phone",url:helper&&helper.session.url,message:t("phone")})}else if(e.type==="request_to_phone"){if(helper&&helper.state==="mac")continueSession()}else if(e.type==="return_to_mac"){if(helper)helper.state="mac";core.seekTo(e.positionSeconds);core.resume();status({phase:"mac",url:helper&&helper.session.url,message:t("mac")})}else if(e.type==="disconnected"){status({phase:"disconnected",url:helper&&helper.session.url,message:t("disconnected")})}else if(e.type==="end"){var wasMac=helper&&helper.state==="mac",message=endingByUser?t("ended"):t("phoneEnded");if(!wasMac){core.seekTo(e.positionSeconds);core.pause()}helper=null;starting=false;endingByUser=false;status({phase:"ended",message:message})}else if(e.type==="expired"){helper=null;starting=false;endingByUser=false;status({phase:"expired",message:t("expired")})}else if(e.type==="error"){status({phase:"error",message:t("processingFailed")})}}
  function onPauseChanged(){if(!helper||mpv.getFlag("pause"))return;if(helper.state==="phone"){core.pause();takeBack()}else if(helper.connected&&helper.state!=="returning")status({phase:"mac",url:helper.session.url,message:t("mac")})}
  function internalStop(){if(!helper)return;var h=helper;helper=null;utils.exec(h.bin+"/continue-helper",["client","--method","POST","--url","http://127.0.0.1:"+h.port+"/control/stop","--secret",h.secret,"--body","{}"]).catch(function(){})}
  function resetForNewFile(){cancelStarting=true;starting=false;endingByUser=false;internalStop();status(baseState())}
  function openSidebar(){loadSidebar(false);sidebar.show();if(sidebarLoaded)deliver(sidebar)}
  menuItem=menu.item(language==="zh"?"开始续播":"Continue on",openSidebar);menu.addItem(menuItem);
  event.on("iina.window-loaded",function(){loadSidebar(true)});loadSidebar(false);checkPlatform();
  ["mpv.track-list.changed","mpv.sid.changed","mpv.secondary-sid.changed","mpv.sub-delay.changed","mpv.secondary-sub-delay.changed"].forEach(function(name){event.on(name,scheduleTrackSync)});
  event.on("mpv.pause.changed",onPauseChanged);
  event.on("iina.file-loaded",resetForNewFile);event.on("iina.window-will-close",function(){cancelStarting=true;internalStop()});
})();
